### ISSUE TITLE
Input file extension

### ISSUE THREAD

**Issue by bio-visualisation** [MintaYLu/COT#7]
What should be the input file extension or file type to start COT analysis? Can you give one example? I have bulk transcriptome-data from three different cell subtypes. Can I use non-normalised gene count file with .txt extension to start this analysis?

**Comment by MintaYLu** [comment]
Hello there,
Thanks for contacting us! 
To address the questions, please see the response below:

> What should be the input file extension or file type to start COT analysis? Can you give one example?

The input data format of `COT` is pandas dataframe, and we also support most of the major input formats, including but not limited to csv, txt, and Gene Expression Omnibus Database (GEO) through third-party packages. For the input data in csv or txt format, the users may convert it into the dataframe using the pandas [read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) function; as for the input data in the GEO format, the data conversion can be done with the [GEOparse](https://geoparse.readthedocs.io/en/latest/index.html) package. The `COT` [example code](https://github.com/MintaYLu/COT/blob/main/Example_GSE28490.ipynb) shows how to import the GEO format data.

>  I have bulk transcriptome-data from three different cell subtypes. Can I use non-normalised gene count file with .txt extension to start this analysis?

Yes, the non-normalised gene count file with `txt` format (assuming the delimiter is `\t`) can definitely be used as the input. You can simply use the following code the read the input data before running the `COT` functions:
`import pandas as pd`
`df_raw = pd.read_csv('data.txt', delimiter='\t', index_col=0)`

Hope it helps! Please feel free to contact us if you have any other questions. Have a good one!

**Comment by MintaYLu** [comment]
> What should be the input file extension or file type to start COT analysis? Can you give one example? I have bulk transcriptome-data from three different cell subtypes. Can I use non-normalised gene count file with .txt extension to start this analysis?
